name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Congratulations!!🎉 on raising your first issue, Our maintainer will review it soon. Keep Contributing!!"
        pr-message: "Congratulations!!🎉 for raising your pull request, Our maintainer will review it soon. Keep Contributing!!"
